
import { RxHamburgerMenu } from 'react-icons/rx';
import { AiOutlineCar } from 'react-icons/ai';
import { GiClothes, GiGardeningShears } from 'react-icons/gi';
import { TbEngine, TbMoodKid } from 'react-icons/tb';
import { BiBuildingHouse, BiHeadphone } from 'react-icons/bi';
import { FaDog, FaIndustry } from 'react-icons/fa';
import { MdHomeRepairService, MdOutlineSportsHandball,  } from 'react-icons/md';

export const allFilters = [
  'usefulSurface',
  'furnished',
  'groundType',
  'commerceType',
  'rooms',
  'compartimentType',
  'floor',
  'landArea',
  'builtArea',
  'constructionYear',
  'model',
  'km',
  'carosery',
  'fuel',
  'engine',
  'year',
  'horsePower',
  'steeringWheel',
  'usefulTask',
  'rezolution',
  'memoryR',
  'videoType',
  'storageType',
  'processorBrand',
  'size',
  'material',
  'season',
  'whichFor',
  'display',
  'waterResistance',
  'caseMaterial',
  'caseColour',
  'soleType',
  'productType',
  'chargeType',
  'mountType',
  'tireSize',
  'tireWidth',
  'tireProfile',
  'rimType',
  'rimSize',
  'age',
  'experience',
  'operationDistance',
  'availability',
  'financePosibility',
  'guarantee',
  'emergencyService',
  'brand',
  'colour',
  'condition',
];
export const mainCategoryArr = [
  {
    im: <RxHamburgerMenu className='img-category'/>,
    id: 1,
    name: 'All',
    value: 'all',
  },
  {
    im: <AiOutlineCar className='img-category'/>,
    id: 2,
    name: 'Auto, Moto, Boats',
    value: 'autoMotoBoats',
  },
  {
    im: <BiBuildingHouse className='img-category'/>,
    id: 3,
    name: 'Real Estate',
    value: 'realEstate',
  },
  {
    im: <BiHeadphone className='img-category'/>,
    id: 4,
    name: 'Electronics, Appliances',
    value: 'electronicsAppliances',
  },
  {
    im: <GiClothes className='img-category'/>,
    id: 5,
    name: 'Fashion',
    value: 'fashion',
  },
  {
    im: <TbEngine className='img-category'/>,
    id: 6,
    name: 'Auto Parts',
    value: 'autoParts',
  },
  {
    im: <GiGardeningShears className='img-category'/>,
    id: 7,
    name: 'House, Gardens',
    value: 'houseAndGarden',
  },
  {
    im: <TbMoodKid className='img-category'/>,
    id: 8,
    name: 'Moms, Kids',
    value: 'momsKids',
  },
  {
    im: <FaDog className='img-category'/>,
    id: 9,
    name: 'Animals',
    value: 'animals',
  },
  {
    im: <MdOutlineSportsHandball className='img-category'/>,
    id: 10,
    name: 'Sport, Free time, Art',
    value: 'sportFreeTimeArt',
  },
  {
    im: <FaIndustry className='img-category'/>,
    id: 11,
    name: 'Agro, Industry',
    value: 'agroIndustry',
  },
  {
    id: 12,
    im: <MdHomeRepairService className='img-category'/>,
    name: 'Services, Company, Equipment',
    value: 'servicesCompanyEquipment',
  },
];
export const mainCategoryCreate = [
  'autoMotoBoats',
  'realEstate',
  'electronicsAppliances',
  'fashion',
  'autoParts',
  'houseAndGarden',
  'momsKids',
  'sportFreeTimeArt',
  'animals',
  'agroIndustry',
  'servicesCompanyEquipment',
];
export const autoBrandsArray = [
  'Abarth',
  'Acura',
  'Aixam',
  'AlfaRomeo',
  'ALPINA',
  'Artega',
  'AsiaMotors',
  'AstonMartin',
  'Audi',
  'Austin',
  'AustinHealey',
  'Bentley',
  'BMW',
  'Borgward',
  'Brilliance',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Casalini',
  'Caterham',
  'Chatenet',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Cobra',
  'Corvette',
  'Cupra',
  'Dacia',
  'Daewoo',
  'Daihatsu',
  'DeTomaso',
  'Dodge',
  'Donkervoort',
  'DSAutomobiles',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'GACGonow',
  'Gemballa',
  'GMC',
  'Grecav',
  'Hamann',
  'Holden',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Iveco',
  'Jaguar',
  'Jeep',
  'Kia',
  'Koenigsegg',
  'KTM',
  'Lamborghini',
  'Lancia',
  'LandRover',
  'Landwind',
  'Lexus',
  'Ligier',
  'Lincoln',
  'Lotus',
  'Mahindra',
  'Maserati',
  'Maybach',
  'Mazda',
  'McLaren',
  'MercedesBenz',
  'MG',
  'Microcar',
  'MINI',
  'Mitsubishi',
  'Morgan',
  'Nissan',
  'Oldsmobile',
  'Opel',
  'Pagani',
  'Peugeot',
  'Piaggio',
  'Plymouth',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Proton',
  'Renault',
  'RollsRoyce',
  'Rover',
  'Saab',
  'Seat',
  'Skoda',
  'Smart',
  'Spyker',
  'Ssangyong',
  'Subaru',
  'Suzuki',
  'Talbot',
  'Tata',
  'Tesla',
  'Toyota',
  'Trabant',
  'Triumph',
  'TVR',
  'Volkswagen',
  'Volvo',
  'Wartburg',
  'Wiesmann',
  'other',
];
export const mainCategoryObj = {
  all: {},
  autoMotoBoats: {
    all: {},
    cars: {
      all: [],
      Abarth: [
        'all',
        '124 Spider',
        '500',
        '500C',
        '595',
        '595C',
        '595 Competizione',
        '595 Turismo',
        '695',
        '695C',
        'Grande Punto',
        'Punto Evo',
        'Other',
      ],
      Acura: ['all', 'MDX', 'NSX', 'RL', 'RSX', 'TL', 'TSX', 'Other'],
      Aixam: ['all', 'City', 'Crossline', 'Roadline', 'Scouty R', 'Other'],
      AlfaRomeo: [
        'all',
        '4C',
        '8C',
        'Alfa 145',
        'Alfa 146',
        'Alfa 147',
        'Alfa 155',
        'Alfa 156',
        'Alfa 159',
        'Alfa 164',
        'Alfa 166',
        'Alfa 33',
        'Alfa 75',
        'Alfa 90',
        'Alfasud',
        'Alfetta',
        'Brera',
        'Crosswagon',
        'Giulia',
        'Giulietta',
        'GT',
        'GTV',
        'Junior',
        'MiTo',
        'Spider',
        'Sprint',
        'Stelvio',
        'Other',
      ],
      ALPINA: [
        'all',
        'B10',
        'B12',
        'B3',
        'B4',
        'B5',
        'B6',
        'B7',
        'B8',
        'D10',
        'D3',
        'D4',
        'D5',
        'Roadster S',
        'XD3',
        'XD4',
        'Other',
      ],
      Artega: ['all', 'GT', 'Other'],
      AsiaMotors: ['all', 'Rocsta', 'Other'],
      AstonMartin: [
        'all',
        'AR1',
        'Cygnet',
        'DB',
        'DB11',
        'DB7',
        'DB9',
        'DBS',
        'Lagonda',
        'Rapide',
        'V12 Vantage',
        'V8 Vantage',
        'Vanquish',
        'Virage',
        'Other',
      ],
      Audi: [
        'all',
        '100',
        '200',
        '80',
        '90',
        'A1',
        'A2',
        'A3',
        'A4',
        'A4 Allroad',
        'A5',
        'A6',
        'A6 Allroad',
        'A7',
        'A8',
        'Cabriolet',
        'Coupé',
        'e-tron',
        'Q1',
        'Q2',
        'Q3',
        'Q5',
        'Q7',
        'Q8',
        'quattro',
        'R8',
        'RS2',
        'RS3',
        'RS4',
        'RS5',
        'RS6',
        'RS7',
        'RSQ3',
        'S1',
        'S2',
        'S3',
        'S4',
        'S5',
        'S6',
        'S7',
        'S8',
        'SQ2',
        'SQ5',
        'SQ7',
        'SQ8',
        'TT',
        'TT RS',
        'TTS',
        'V8',
        'Other',
      ],

      Austin: ['all', 'Other'],
      AustinHealey: ['all', 'Other'],
      Bentley: [
        'all',
        'Arnage',
        'Azure',
        'Bentayga',
        'Brooklands',
        'Continental',
        'Continental Flying Spur',
        'Continental GT',
        'Continental GTC',
        'Continental Supersports',
        'Eight',
        'Flying Spur',
        'Mulsanne',
        'Turbo R',
        'Turbo RT',
        'Turbo S',
        'Other',
      ],
      BMW: [
        'all',
        '114',
        '116',
        '118',
        '120',
        '123',
        '125',
        '130',
        '135',
        '1er M Coupé',
        '2002',
        '214 Active Tourer',
        '214 Gran Tourer',
        '216',
        '216 Active Tourer',
        '216 Gran Tourer',
        '218',
        '218 Active Tourer',
        '218 Gran Tourer',
        '220',
        '220 Active Tourer',
        '220 Gran Tourer',
        '225',
        '225 Active Tourer',
        '228',
        '230',
        '315',
        '316',
        '318',
        '318 Gran Turismo',
        '320',
        '320 Gran Turismo',
        '323',
        '324',
        '325',
        '325 Gran Turismo',
        '328',
        '328 Gran Turismo',
        '330',
        '330 Gran Turismo',
        '335',
        '335 Gran Turismo',
        '340',
        '340 Gran Turismo',
        'ActiveHybrid 3',
        '418',
        '418 Gran Coupé',
        '420',
        '420 Gran Coupé',
        '425',
        '425 Gran Coupé',
        '428',
        '428 Gran Coupé',
        '430',
        '430 Gran Coupé',
        '435',
        '435 Gran Coupé',
        '440',
        '440 Gran Coupé',
        '518',
        '520',
        '520 Gran Turismo',
        '523',
        '524',
        '525',
        '528',
        '530',
        '530 Gran Turismo',
        '535',
        '535 Gran Turismo',
        '540',
        '545',
        '550',
        '550 Gran Turismo',
        'ActiveHybrid 5',
        '620 Gran Turismo',
        '628',
        '630',
        '630 Gran Turismo',
        '633',
        '635',
        '640',
        '640 Gran Coupé',
        '640 Gran Turismo',
        '645',
        '650',
        '650 Gran Coupé',
        '725',
        '728',
        '730',
        '732',
        '735',
        '740',
        '745',
        '750',
        '760',
        'ActiveHybrid 7',
        '840',
        '850',
        'i3',
        'i8',
        'M135',
        'M140i',
        'M2',
        'M235',
        'M240i',
        'M3',
        'M340i',
        'M4',
        'M5',
        'M550',
        'M6',
        'M760',
        'M850',
        'ActiveHybrid X6',
        'X1',
        'X2',
        'X3',
        'X3 M',
        'X3 M40',
        'X4',
        'X4 M',
        'X4 M40',
        'X5',
        'X5 M',
        'X5 M50',
        'X6',
        'X6 M',
        'X6 M50',
        'X7',
        'Z1',
        'Z3',
        'Z3 M',
        'Z4',
        'Z4 M',
        'Z8',
        'Other',
      ],
      Borgward: ['all', 'Other'],
      Brilliance: ['all', 'BC3', 'BS2', 'BS4', 'BS6', 'Other'],
      Bugatti: ['all', 'Chiron', 'EB 110', 'Veyron', 'Other'],
      Buick: [
        'all',
        'Century',
        'Electra',
        'Enclave',
        'La Crosse',
        'Le Sabre',
        'Park Avenue',
        'Regal',
        'Riviera',
        'Roadmaster',
        'Skylark',
        'Other',
      ],
      Cadillac: [
        'all',
        'Allante',
        'ATS',
        'BLS',
        'CT6',
        'CTS',
        'Deville',
        'Eldorado',
        'Escalade',
        'Fleetwood',
        'Seville',
        'SRX',
        'STS',
        'XLR',
        'XT5',
        'Other',
      ],
      Casalini: ['all', 'Other'],
      Caterham: ['all', 'Other'],
      Chatenet: ['all', 'Other'],
      Chevrolet: [
        'all',
        '2500',
        'Alero',
        'Astro',
        'Avalanche',
        'Aveo',
        'Beretta',
        'Blazer',
        'C1500',
        'Camaro',
        'Caprice',
        'Captiva',
        'Cavalier',
        'Chevelle',
        'Chevy Van',
        'Citation',
        'Colorado',
        'Corsica',
        'Cruze',
        'El Camino',
        'Epica',
        'Evanda',
        'Express',
        'G',
        'HHR',
        'Impala',
        'K1500',
        'K30',
        'Kalos',
        'Lacetti',
        'Lumina',
        'Malibu',
        'Matiz',
        'Niva',
        'Nubira',
        'Orlando',
        'Rezzo',
        'S-10',
        'Silverado',
        'Spark',
        'SSR',
        'Suburban',
        'Tahoe',
        'Trailblazer',
        'Trans Sport',
        'Traverse',
        'Trax',
        'Venture',
        'Volt',
        'Other',
      ],
      Chrysler: [
        'all',
        '200',
        '300C',
        '300 M',
        'Aspen',
        'Crossfire',
        'Daytona',
        'ES',
        'Grand Voyager',
        'GS',
        'GTS',
        'Imperial',
        'Le Baron',
        'Neon',
        'New Yorker',
        'Pacifica',
        'PT Cruiser',
        'Saratoga',
        'Sebring',
        'Stratus',
        'Valiant',
        'Viper',
        'Vision',
        'Voyager',
        'Other',
      ],
      Citroën: [
        'all',
        '2 CV',
        'AX',
        'Berlingo',
        'BX',
        'C1',
        'C2',
        'C3',
        'C3 Aircross',
        'C3 Picasso',
        'C4',
        'C4 Aircross',
        'C4 Cactus',
        'C4 Picasso',
        'C4 SpaceTourer',
        'C5',
        'C5 Aircross',
        'C6',
        'C8',
        'C-Crosser',
        'C-Elysée',
        'CX',
        'C-Zero',
        'DS',
        'DS3',
        'DS4',
        'DS4 Crossback',
        'DS5',
        'E-MEHARI',
        'Evasion',
        'Grand C4 Picasso / SpaceTourer',
        'GSA',
        'Jumper',
        'Jumpy',
        'Nemo',
        'SAXO',
        'SM',
        'SpaceTourer',
        'Visa',
        'Xantia',
        'XM',
        'Xsara',
        'Xsara Picasso',
        'ZX',
        'Other',
      ],
      Cobra: ['all', 'Other'],
      Corvette: [
        'all',
        'C1',
        'C2',
        'C3',
        'C4',
        'C5',
        'C6',
        'C7',
        'C8',
        'Z06',
        'ZR 1',
        'Other',
      ],
      Cupra: ['all', 'Arona', 'Ateca', 'Ibiza', 'Other'],
      Dacia: [
        'all',
        'Dokker',
        'Duster',
        'Lodgy',
        'Logan',
        'Logan Pick-Up',
        'Pick Up',
        'Sandero',
        'Other',
      ],
      Daewoo: [
        'all',
        'Espero',
        'Evanda',
        'Kalos',
        'Korando',
        'Lacetti',
        'Lanos',
        'Leganza',
        'Matiz',
        'Musso',
        'Nexia',
        'Nubira',
        'Rezzo',
        'Tacuma',
        'Other',
      ],
      Daihatsu: [
        'all',
        'Applause',
        'Charade',
        'Charmant',
        'Copen',
        'Cuore',
        'Feroza/Sportrak',
        'Freeclimber',
        'Gran Move',
        'Hijet',
        'MATERIA',
        'Move',
        'Rocky/Fourtrak',
        'Sirion',
        'Terios',
        'TREVIS',
        'YRV',
        'Other',
      ],
      DeTomaso: ['all', 'Guarà', 'Pantera', 'Other'],
      Dodge: [
        'all',
        'Avenger',
        'Caliber',
        'Challenger',
        'Charger',
        'Dakota',
        'Dart',
        'Demon',
        'Durango',
        'Grand Caravan',
        'Hornet',
        'Journey',
        'Magnum',
        'Neon',
        'Nitro',
        'RAM',
        'Stealth',
        'Viper',
        'Other',
      ],
      Donkervoort: ['all', 'D8', 'S7', 'S8', 'Other'],
      DSAutomobiles: [
        'all',
        'DS3',
        'DS3 Crossback',
        'DS4',
        'DS4 Crossback',
        'DS5',
        'DS7 Crossback',
        'Other',
      ],
      Ferrari: [
        'all',
        '208',
        '246',
        '250',
        '275',
        '288',
        '308',
        '328',
        '330',
        '348',
        '360',
        '365',
        '400',
        '412',
        '456',
        '458',
        '488 GTB',
        '488 Pista',
        '488 Spider',
        '512',
        '550',
        '575',
        '599 GTB',
        '599 GTO',
        '599 SA Aperta',
        '612',
        '750',
        '812',
        'California',
        'Daytona',
        'Dino GT4',
        'Enzo Ferrari',
        'F12',
        'F355',
        'F40',
        'F430',
        'F50',
        'FF',
        'GTC4Lusso',
        'LaFerrari',
        'Mondial',
        'Portofino',
        'Superamerica',
        'Testarossa',
        'Other',
      ],
      Fiat: [
        'all',
        '124',
        '124 Spider',
        '126',
        '127',
        '130',
        '131',
        '500',
        '500C',
        '500L',
        '500L Cross',
        '500L Living',
        '500L Trekking',
        '500L Urban',
        '500L Wagon',
        '500S',
        '500X',
        'Albea',
        'Barchetta',
        'Brava',
        'Bravo',
        'Cinquecento',
        'Coupe',
        'Croma',
        'Dino',
        'Doblo',
        'Ducato',
        'Fiorino',
        'Freemont',
        'Fullback',
        'Grande Punto',
        'Idea',
        'Linea',
        'Marea',
        'Marengo',
        'Multipla',
        'New Panda',
        'Palio',
        'Panda',
        'Punto',
        'Punto Evo',
        'Qubo',
        'Regata',
        'Ritmo',
        'Scudo',
        'Sedici',
        'Seicento',
        'Siena',
        'Spider Europa',
        'Stilo',
        'Strada',
        'Talento',
        'Tempra',
        'Tipo',
        'Ulysse',
        'Uno',
        'X 1/9',
        'Other',
      ],
      Fisker: ['all', 'Karma', 'Other'],
      Ford: [
        'all',
        'Aerostar',
        'B-Max',
        'Bronco',
        'Capri',
        'C-Max',
        'Cougar',
        'Courier',
        'Crown',
        'Econoline',
        'Econovan',
        'EcoSport',
        'Edge',
        'Escape',
        'Escort',
        'Excursion',
        'Expedition',
        'Explorer',
        'Express',
        'F 100',
        'F 150',
        'F 250',
        'F 350',
        'Fairlane',
        'Falcon',
        'Fiesta',
        'Flex',
        'Focus',
        'Fusion',
        'Galaxy',
        'Granada',
        'Grand C-Max',
        'Grand Tourneo',
        'GT',
        'Ka/Ka+',
        'Kuga',
        'Maverick',
        'Mercury',
        'Mondeo',
        'Mustang',
        'Orion',
        'Probe',
        'Puma',
        'Ranger',
        'Raptor',
        'Scorpio',
        'Sierra',
        'S-Max',
        'Sportka',
        'Streetka',
        'Taunus',
        'Taurus',
        'Thunderbird',
        'Tourneo',
        'Tourneo Connect',
        'Tourneo Courier',
        'Tourneo Custom',
        'Transit',
        'Transit Connect',
        'Transit Courier',
        'Transit Custom',
        'Windstar',
        'Other',
      ],
      GACGonow: ['all', 'Other'],
      Gemballa: ['all', 'Other'],
      GMC: [
        'all',
        'Acadia',
        'Envoy',
        'Safari',
        'Savana',
        'Sierra',
        'Sonoma',
        'Syclone',
        'Terrain',
        'Typhoon',
        'Vandura',
        'Yukon',
        'Other',
      ],
      Grecav: ['all', 'Sonique', 'Other'],
      Hamann: ['all', 'Other'],
      Holden: ['all', 'Other'],
      Honda: [
        'all',
        'Accord',
        'Aerodeck',
        'City',
        'Civic',
        'Clarity',
        'Concerto',
        'CR-V',
        'CRX',
        'CR-Z',
        'e',
        'Element',
        'FR-V',
        'HR-V',
        'Insight',
        'Integra',
        'Jazz',
        'Legend',
        'Logo',
        'NSX',
        'Odyssey',
        'Pilot',
        'Prelude',
        'Ridgeline',
        'S2000',
        'Shuttle',
        'Stream',
        'Other',
      ],
      Hummer: ['all', 'H1', 'H2', 'H3', 'Other'],
      Hyundai: [
        'all',
        'Accent',
        'Atos',
        'Azera',
        'Coupe',
        'Elantra',
        'Excel',
        'Galloper',
        'Genesis',
        'Getz',
        'Grandeur',
        'Grand Santa Fe',
        'H-1',
        'H 100',
        'H-1 Starex',
        'H 200',
        'H350',
        'i10',
        'i20',
        'i30',
        'i40',
        'i50',
        'IONIQ',
        'ix20',
        'ix35',
        'ix55',
        'Kona',
        'Lantra',
        'Matrix',
        'Nexo',
        'Pony',
        'Santa Fe',
        'Santamo',
        'S-Coupe',
        'Sonata',
        'Terracan',
        'Trajet',
        'Tucson',
        'Veloster',
        'Veracruz',
        'XG 30',
        'XG 350',
        'Other',
      ],
      Infiniti: [
        'all',
        'EX30',
        'EX35',
        'EX37',
        'FX',
        'G35',
        'G37',
        'M30',
        'M35',
        'M37',
        'Q30',
        'Q45',
        'Q50',
        'Q60',
        'Q70',
        'QX30',
        'QX50',
        'QX56',
        'QX70',
        'Other',
      ],
      Isuzu: [
        'all',
        'Campo',
        'D-Max',
        'Gemini',
        'Midi',
        'PICK UP',
        'Trooper',
        'Other',
      ],
      Iveco: ['all', 'Massif', 'Other'],
      Jaguar: [
        'all',
        'Daimler',
        'E-Pace',
        'E-Type',
        'F-Pace',
        'F-Type',
        'I-Pace',
        'MK II',
        'S-Type',
        'XE',
        'XF',
        'XJ',
        'XJ12',
        'XJ40',
        'XJ6',
        'XJ8',
        'XJR',
        'XJS',
        'XJSC',
        'XK',
        'XK8',
        'XKR',
        'X-Type',
        'Other',
      ],
      Jeep: [
        'all',
        'Cherokee',
        'CJ',
        'Comanche',
        'Commander',
        'Compass',
        'Grand Cherokee',
        'Patriot',
        'Renegade',
        'Wagoneer',
        'Willys',
        'Wrangler',
        'Other',
      ],
      Kia: [
        'all',
        'Besta',
        'Borrego',
        'Carens',
        'Carnival',
        "cee'd / Ceed",
        "cee'd Sportswagon",
        'Cerato',
        'Clarus',
        'Elan',
        'Joice',
        'K2500',
        'K2700',
        'Leo',
        'Magentis',
        'Mentor',
        'Mini',
        'Niro',
        'Opirus',
        'Optima',
        'Picanto',
        'Pregio',
        'Pride',
        "pro_cee'd / ProCeed",
        'Retona',
        'Rio',
        'Roadster',
        'Rocsta',
        'Sephia',
        'Shuma',
        'Sorento',
        'Soul',
        'Sportage',
        'Stinger',
        'Stonic',
        'Venga',
        'XCeed',
        'Other',
      ],
      Koenigsegg: ['all', 'Agera', 'CCR', 'CCXR', 'Other'],
      KTM: ['all', 'X-BOW', 'Other'],

      Lamborghini: [
        'all',
        'Aventador',
        'Countach',
        'Diablo',
        'Espada',
        'Gallardo',
        'Huracán',
        'Jalpa',
        'LM',
        'Miura',
        'Murciélago',
        'Urraco',
        'Urus',
        'Other',
      ],
      Lancia: [
        'all',
        'Beta',
        'Dedra',
        'Delta',
        'Flaminia',
        'Flavia',
        'Fulvia',
        'Gamma',
        'Kappa',
        'Lybra',
        'MUSA',
        'Phedra',
        'Prisma',
        'Stratos',
        'Thema',
        'Thesis',
        'Voyager',
        'Ypsilon',
        'Zeta',
        'Other',
      ],
      LandRover: [
        'all',
        'Defender',
        'Discovery',
        'Discovery Sport',
        'Freelander',
        'Range Rover',
        'Range Rover Evoque',
        'Range Rover Sport',
        'Range Rover Velar',
        'Serie I',
        'Serie II',
        'Serie III',
        'Other',
      ],
      Landwind: ['all', 'CV-9', 'S', 'SC2', 'SC4', 'Other'],
      Lexus: [
        'all',
        'CT 200h',
        'ES 300',
        'ES 330',
        'ES 350',
        'GS 250',
        'GS 300',
        'GS 350',
        'GS 430',
        'GS 450',
        'GS 460',
        'GS F',
        'GX 470',
        'IS 200',
        'IS 220',
        'IS 250',
        'IS 300',
        'IS 350',
        'IS-F',
        'LC 500',
        'LC 500h',
        'LFA',
        'LS 400',
        'LS 430',
        'LS 460',
        'LS 500',
        'LS 600',
        'LX 470',
        'LX 570',
        'NX 200',
        'NX 300',
        'RC 200',
        'RC 300',
        'RC 350',
        'RC F',
        'RX 200',
        'RX 300',
        'RX 330',
        'RX 350',
        'RX 400',
        'RX 450',
        'SC 400',
        'SC 430',
        'UX',
        'Other',
      ],
      Ligier: [
        'all',
        'Ambra',
        'Be Sun',
        'JS 50',
        'JS 50 L',
        'JS RC',
        'Nova',
        'Optima',
        'X - Too',
        'Other',
      ],
      Lincoln: [
        'all',
        'Aviator',
        'Continental',
        'LS',
        'Mark',
        'Navigator',
        'Town Car',
        'Other',
      ],
      Lotus: [
        'all',
        '340 R',
        'Cortina',
        'Elan',
        'Elise',
        'Elite',
        'Esprit',
        'Europa',
        'Evora',
        'Excel',
        'Exige',
        'Super Seven',
        'Other',
      ],
      Mahindra: ['all', 'Other'],
      Maserati: [
        'all',
        '222',
        '224',
        '228',
        '3200',
        '418',
        '420',
        '4200',
        '422',
        '424',
        '430',
        'Biturbo',
        'Ghibli',
        'GranCabrio',
        'Gransport',
        'Granturismo',
        'Indy',
        'Karif',
        'Levante',
        'MC12',
        'Merak',
        'Quattroporte',
        'Shamal',
        'Spyder',
        'Other',
      ],
      Maybach: ['all', '57', '62', 'Pullman', 'Other'],
      Mazda: [
        'all',
        '121',
        '2',
        '3',
        '323',
        '5',
        '6',
        '626',
        '929',
        'Bongo',
        'B series',
        'BT-50',
        'CX-3',
        'CX-30',
        'CX-5',
        'CX-7',
        'CX-9',
        'Demio',
        'E series',
        'Millenia',
        'MPV',
        'MX-3',
        'MX-5',
        'MX-6',
        'Premacy',
        'Protege',
        'RX-6',
        'RX-7',
        'RX-8',
        'Tribute',
        'Xedos',
        'Other',
      ],
      McLaren: [
        'all',
        '540C',
        '570GT',
        '570S',
        '650S',
        '650S Coupé',
        '650S Spider',
        '675LT',
        '675LT Spider',
        '720S',
        'GT',
        'MP4-12C',
        'P1',
        'Other',
      ],
      MercedesBenz: [
        'all',
        '190',
        '200',
        '220',
        '230',
        '240',
        '250',
        '260',
        '270',
        '280',
        '290',
        '300',
        '320',
        '350',
        '380',
        '400',
        '416',
        '420',
        '450',
        '500',
        '560',
        '600',
        'A 140',
        'A 150',
        'A 160',
        'A 170',
        'A 180',
        'A 190',
        'A 200',
        'A 210',
        'A 220',
        'A 250',
        'A 35 AMG',
        'A 45 AMG',
        'B 150',
        'B 160',
        'B 170',
        'B 180',
        'B 200',
        'B 220',
        'B 250',
        'B Electric Drive',
        'C 160',
        'C 180',
        'C 200',
        'C 220',
        'C 230',
        'C 240',
        'C 250',
        'C 270',
        'C 280',
        'C 300',
        'C 30 AMG',
        'C 320',
        'C 32 AMG',
        'C 350',
        'C 36 AMG',
        'C 400',
        'C 43 AMG',
        'C 450 AMG',
        'C 55 AMG',
        'C 63 AMG',
        'CE 200',
        'CE 220',
        'CE 230',
        'CE 280',
        'CE 300',
        'CE 320',
        'Citan',
        'CLA 180',
        'CLA 180 Shooting Brake',
        'CLA 200',
        'CLA 200 Shooting Brake',
        'CLA 220',
        'CLA 220 Shooting Brake',
        'CLA 250',
        'CLA 250 Shooting Brake',
        'CLA 35 AMG',
        'CLA 45 AMG',
        'CLA 45 AMG Shooting Brake',
        'CLA Shooting Brake',
        'CLC 160',
        'CLC 180',
        'CLC 200',
        'CLC 220',
        'CLC 230',
        'CLC 250',
        'CLC 350',
        'CL 160',
        'CL 180',
        'CL 200',
        'CL 220',
        'CL 230',
        'CL 320',
        'CL 420',
        'CL 500',
        'CL 55 AMG',
        'CL 600',
        'CL 63 AMG',
        'CL 65 AMG',
        'CLK 200',
        'CLK 220',
        'CLK 230',
        'CLK 240',
        'CLK 270',
        'CLK 280',
        'CLK 320',
        'CLK 350',
        'CLK 430',
        'CLK 500',
        'CLK 55 AMG',
        'CLK 63 AMG',
        'CLS 220',
        'CLS 220 Shooting Brake',
        'CLS 250',
        'CLS 250 Shooting Brake',
        'CLS 280',
        'CLS 300',
        'CLS 320',
        'CLS 350',
        'CLS 350 Shooting Brake',
        'CLS 400',
        'CLS 400 Shooting Brake',
        'CLS 450',
        'CLS 500',
        'CLS 500 Shooting Brake',
        'CLS 53 AMG',
        'CLS 55 AMG',
        'CLS 63 AMG',
        'CLS 63 AMG Shooting Brake',
        'CLS Shooting Brake',
        'E 200',
        'E 220',
        'E 230',
        'E 240',
        'E 250',
        'E 260',
        'E 270',
        'E 280',
        'E 290',
        'E 300',
        'E 320',
        'E 350',
        'E 36 AMG',
        'E 400',
        'E 420',
        'E 430',
        'E 43 AMG',
        'E 450',
        'E 50',
        'E 500',
        'E 53 AMG',
        'E 55 AMG',
        'E 60 AMG',
        'E 63 AMG',
        'EQC',
        'G 230',
        'G 240',
        'G 250',
        'G 270',
        'G 280',
        'G 290',
        'G 300',
        'G 320',
        'G 350',
        'G 400',
        'G 500',
        'G 55 AMG',
        'G 63 AMG',
        'G 65 AMG',
        'GLA 180',
        'GLA 200',
        'GLA 220',
        'GLA 250',
        'GLA 45 AMG',
        'GLB 180',
        'GLB 200',
        'GLB 220',
        'GLB 250',
        'GLC 200',
        'GLC 220',
        'GLC 250',
        'GLC 300',
        'GLC 350',
        'GLC 400',
        'GLC 43 AMG',
        'GLC 63 AMG',
        'GL 320',
        'GL 350',
        'GL 400',
        'GL 420',
        'GL 450',
        'GL 500',
        'GL 55 AMG',
        'GL 63 AMG',
        'GLE 250',
        'GLE 300',
        'GLE 350',
        'GLE 400',
        'GLE 43 AMG',
        'GLE 450',
        'GLE 500',
        'GLE 53 AMG',
        'GLE 63 AMG',
        'GLK 200',
        'GLK 220',
        'GLK 250',
        'GLK 280',
        'GLK 300',
        'GLK 320',
        'GLK 350',
        'GLS 350',
        'GLS 400',
        'GLS 500',
        'GLS 63',
        'AMG GT',
        'AMG GT C',
        'AMG GT R',
        'AMG GT S',
        'MB 100',
        'ML 230',
        'ML 250',
        'ML 270',
        'ML 280',
        'ML 300',
        'ML 320',
        'ML 350',
        'ML 400',
        'ML 420',
        'ML 430',
        'ML 450',
        'ML 500',
        'ML 55 AMG',
        'ML 63 AMG',
        'R 280',
        'R 300',
        'R 320',
        'R 350',
        'R 500',
        'R 63 AMG',
        'S 250',
        'S 260',
        'S 280',
        'S 300',
        'S 320',
        'S 350',
        'S 400',
        'S 420',
        'S 430',
        'S 450',
        'S 500',
        'S 55',
        'S 550',
        'S 560',
        'S 600',
        'S 63 AMG',
        'S 650',
        'S 65 AMG',
        'SLC 180',
        'SLC 200',
        'SLC 250',
        'SLC 280',
        'SLC 300',
        'SLC 43 AMG',
        'SL 280',
        'SL 300',
        'SL 320',
        'SL 350',
        'SL 380',
        'SL 400',
        'SL 420',
        'SL 450',
        'SL 500',
        'SL 55 AMG',
        'SL 560',
        'SL 600',
        'SL 60 AMG',
        'SL 63 AMG',
        'SL 65 AMG',
        'SL 70 AMG',
        'SL 73 AMG',
        'SLK 200',
        'SLK 230',
        'SLK 250',
        'SLK 280',
        'SLK 300',
        'SLK 320',
        'SLK 32 AMG',
        'SLK 350',
        'SLK 55 AMG',
        'SLR',
        'SLS AMG',
        'Sprinter',
        'Vaneo',
        'Vario',
        'V 200',
        'V 220',
        'V 230',
        'V 250',
        'V 280',
        'V 300',
        'Viano',
        'Vito',
        'X 220',
        'X 250',
        'X 350',
        'Other',
      ],
      MG: [
        'all',
        'MGA',
        'MGB',
        'MGF',
        'Midget',
        'Montego',
        'TD',
        'TF',
        'ZR',
        'ZS',
        'ZT',
        'Other',
      ],
      Microcar: [
        'all',
        'DUÈ',
        'Flex',
        'M.Go',
        'M-8',
        'MC1',
        'MC2',
        'Virgo',
        'Other',
      ],
      MINI: [
        'all',
        'Cooper Cabrio',
        'Cooper D Cabrio',
        'Cooper S Cabrio',
        'Cooper SD Cabrio',
        'John Cooper Works Cabrio',
        'One Cabrio',
        'Cooper Clubman',
        'Cooper D Clubman',
        'Cooper S Clubman',
        'Cooper SD Clubman',
        'John Cooper Works Clubman',
        'One Clubman',
        'One D Clubman',
        'Clubvan',
        'Cooper Countryman',
        'Cooper D Countryman',
        'Cooper S Countryman',
        'Cooper SD Countryman',
        'John Cooper Works Countryman',
        'One Countryman',
        'One D Countryman',
        'Cooper Coupé',
        'Cooper S Coupé',
        'Cooper SD Coupé',
        'John Cooper Works Coupé',
        '1000',
        '1300',
        'Cooper',
        'Cooper D',
        'Cooper S',
        'Cooper SD',
        'John Cooper Works',
        'ONE',
        'One D',
        'One First',
        'Cooper D Paceman',
        'Cooper Paceman',
        'Cooper SD Paceman',
        'Cooper S Paceman',
        'John Cooper Works Paceman',
        'Cooper Roadster',
        'Cooper SD Roadster',
        'Cooper S Roadster',
        'John Cooper Works Roadster',
        'Other',
      ],
      Mitsubishi: [
        'all',
        '3000 GT',
        'ASX',
        'Canter',
        'Carisma',
        'Colt',
        'Cordia',
        'Cosmos',
        'Diamante',
        'Eclipse',
        'Eclipse Cross',
        'Galant',
        'Galloper',
        'Grandis',
        'i-MiEV',
        'L200',
        'L300',
        'L400',
        'Lancer',
        'Mirage',
        'Montero',
        'Outlander',
        'Pajero',
        'Pajero Pinin',
        'Pick-up',
        'Plug-in Hybrid Outlander',
        'Santamo',
        'Sapporo',
        'Sigma',
        'Space Gear',
        'Space Runner',
        'Space Star',
        'Space Wagon',
        'Starion',
        'Tredia',
        'Other',
      ],
      Morgan: [
        'all',
        '3 Wheeler',
        '4/4',
        'Aero 8',
        'Plus 4',
        'Plus 8',
        'Roadster',
        'Other',
      ],
      Nissan: [
        'all',
        '100 NX',
        '200 SX',
        '240 SX',
        '280 ZX',
        '300 ZX',
        '350Z',
        '370Z',
        'Almera',
        'Almera Tino',
        'Altima',
        'Armada',
        'Bluebird',
        'Cabstar',
        'Cargo',
        'Cherry',
        'Cube',
        'e-NV200',
        'Evalia',
        'Frontier',
        'GT-R',
        'Interstar',
        'Juke',
        'King Cab',
        'Kubistar',
        'Laurel',
        'Leaf',
        'Maxima',
        'Micra',
        'Murano',
        'Navara',
        'Note',
        'NP 300',
        'NV200',
        'NV250',
        'NV300',
        'NV400',
        'Pathfinder',
        'Patrol',
        'PickUp',
        'Pixo',
        'Prairie',
        'Primastar',
        'Primera',
        'Pulsar',
        'Qashqai',
        'Qashqai+2',
        'Quest',
        'Sentra',
        'Serena',
        'Silvia',
        'Skyline',
        'Sunny',
        'Terrano',
        'Tiida',
        'Titan',
        'Trade',
        'Urvan',
        'Vanette',
        'X-Trail',
        'Other',
      ],
      Oldsmobile: [
        'all',
        'Bravada',
        'Custom Cruiser',
        'Cutlass',
        'Delta 88',
        'Silhouette',
        'Supreme',
        'Toronado',
        'Other',
      ],
      Opel: [
        'all',
        'Adam',
        'Agila',
        'Ampera',
        'Ampera-e',
        'Antara',
        'Arena',
        'Ascona',
        'Astra',
        'Calibra',
        'Campo',
        'Cascada',
        'Cavalier',
        'Combo',
        'Commodore',
        'Corsa',
        'Crossland X',
        'Diplomat',
        'Frontera',
        'Grandland X',
        'GT',
        'Insignia',
        'Insignia CT',
        'Kadett',
        'Karl',
        'Manta',
        'Meriva',
        'Mokka',
        'Mokka X',
        'Monterey',
        'Monza',
        'Movano',
        'Nova',
        'Omega',
        'Pick Up Sportscap',
        'Rekord',
        'Senator',
        'Signum',
        'Sintra',
        'Speedster',
        'Tigra',
        'Vectra',
        'Vivaro',
        'Zafira',
        'Zafira Life',
        'Zafira Tourer',
        'Other',
      ],
      Pagani: ['all', 'Huayra', 'Zonda', 'Other'],
      Peugeot: [
        'all',
        '1007',
        '104',
        '106',
        '107',
        '108',
        '2008',
        '204',
        '205',
        '206',
        '207',
        '208',
        '3008',
        '301',
        '304',
        '305',
        '306',
        '307',
        '308',
        '309',
        '4007',
        '4008',
        '404',
        '405',
        '406',
        '407',
        '5008',
        '504',
        '505',
        '508',
        '604',
        '605',
        '607',
        '806',
        '807',
        'Bipper',
        'Bipper Tepee',
        'Boxer',
        'Expert',
        'Expert Tepee',
        'iOn',
        'J5',
        'Partner',
        'Partner Tepee',
        'RCZ',
        'Rifter',
        'TePee',
        'Traveller',
        'Other',
      ],
      Piaggio: ['all', 'APE', 'APE TM', 'Porter', 'Other'],
      Plymouth: ['all', 'Prowler', 'Other'],
      Polestar: ['all', '1', 'Other'],
      Pontiac: [
        'all',
        '6000',
        'Bonneville',
        'Fiero',
        'Firebird',
        'G6',
        'Grand-Am',
        'Grand-Prix',
        'GTO',
        'Montana',
        'Solstice',
        'Sunbird',
        'Sunfire',
        'Targa',
        'Trans Am',
        'Trans Sport',
        'Vibe',
        'Other',
      ],
      Porsche: [
        'all',
        '356',
        '912',
        '914',
        '918',
        '924',
        '928',
        '944',
        '959',
        '962',
        '968',
        'Boxster',
        'Carrera GT',
        'Cayenne',
        'Cayman',
        'Macan',
        'Panamera',
        '911',
        '930',
        '964',
        '991',
        '992',
        '993',
        '996',
        '997',
        'Taycan',
        'Other',
      ],
      Proton: ['all', '300 Serie', '400 Serie', 'Other'],
      Renault: [
        'all',
        'Alaskan',
        'Alpine A110',
        'Alpine A310',
        'Alpine V6',
        'Avantime',
        'Captur',
        'Clio',
        'Coupe',
        'Espace',
        'Express',
        'Fluence',
        'Fuego',
        'Grand Espace',
        'Grand Modus',
        'Grand Scenic',
        'Kadjar',
        'Kangoo',
        'Koleos',
        'Laguna',
        'Latitude',
        'Mascott',
        'Master',
        'Megane',
        'Modus',
        'P 1400',
        'R 11',
        'R 14',
        'R 18',
        'R 19',
        'R 20',
        'R 21',
        'R 25',
        'R 30',
        'R 4',
        'R 5',
        'R 6',
        'R 9',
        'Rapid',
        'Safrane',
        'Scenic',
        'Spider',
        'Talisman',
        'Trafic',
        'Twingo',
        'Twizy',
        'Vel Satis',
        'Wind',
        'ZOE',
        'Other',
      ],
      RollsRoyce: [
        'all',
        'Corniche',
        'Cullinan',
        'Dawn',
        'Flying Spur',
        'Ghost',
        'Park Ward',
        'Phantom',
        'Silver Cloud',
        'Silver Dawn',
        'Silver Seraph',
        'Silver Shadow',
        'Silver Spirit',
        'Silver Spur',
        'Wraith',
        'Other',
      ],
      Rover: [
        'all',
        '100',
        '111',
        '114',
        '115',
        '200',
        '213',
        '214',
        '216',
        '218',
        '220',
        '25',
        '400',
        '414',
        '416',
        '418',
        '420',
        '45',
        '600',
        '618',
        '620',
        '623',
        '75',
        '800',
        '820',
        '825',
        '827',
        'City Rover',
        'Metro',
        'Montego',
        'SD',
        'Streetwise',
        'Other',
      ],
      Saab: [
        'all',
        '90',
        '900',
        '9000',
        '9-3',
        '9-4X',
        '9-5',
        '96',
        '9-7X',
        '99',
        'Other',
      ],
      Seat: [
        'all',
        'Alhambra',
        'Altea',
        'Arona',
        'Arosa',
        'Ateca',
        'Cordoba',
        'Exeo',
        'Ibiza',
        'Inca',
        'Leon',
        'Malaga',
        'Marbella',
        'Mii',
        'Tarraco',
        'Terra',
        'Toledo',
        'Other',
      ],
      Skoda: [
        'all',
        '105',
        '120',
        '130',
        '135',
        'Citigo',
        'Fabia',
        'Favorit',
        'Felicia',
        'Forman',
        'Kamiq',
        'Karoq',
        'Kodiaq',
        'Octavia',
        'Pick-up',
        'Praktik',
        'Rapid',
        'Roomster',
        'Scala',
        'Superb',
        'Yeti',
        'Other',
      ],
      Smart: ['all', 'Crossblade', 'ForFour', 'ForTwo', 'Roadster', 'Other'],
      Spyker: [
        'all',
        'C8',
        'C8 AILERON',
        'C8 DOUBLE 12 S',
        'C8 LAVIOLETTE SWB',
        'C8 SPYDER SWB',
        'Other',
      ],
      Ssangyong: [
        'all',
        'Actyon',
        'Family',
        'Korando',
        'Kyron',
        'MUSSO',
        'REXTON',
        'Rodius',
        'Tivoli',
        'XLV',
        'Other',
      ],
      Subaru: [
        'all',
        'B9 Tribeca',
        'Baja',
        'BRZ',
        'Forester',
        'Impreza',
        'Justy',
        'Legacy',
        'Levorg',
        'Libero',
        'Outback',
        'SVX',
        'Trezia',
        'Tribeca',
        'Vivio',
        'WRX STI',
        'XT',
        'XV',
        'Other',
      ],
      Suzuki: [
        'all',
        'Alto',
        'Baleno',
        'Cappuccino',
        'Carry',
        'Celerio',
        'Grand Vitara',
        'Ignis',
        'iK-2',
        'Jimny',
        'Kizashi',
        'Liana',
        'LJ',
        'SJ Samurai',
        'Splash',
        'Super-Carry',
        'Swift',
        'SX4',
        'SX4 S-Cross',
        'Vitara',
        'Wagon R+',
        'X-90',
        'Other',
      ],
      Talbot: ['all', 'Horizon', 'Samba', 'Other'],
      Tata: [
        'all',
        'Indica',
        'Indigo',
        'Nano',
        'Safari',
        'Sumo',
        'Telcoline',
        'Telcosport',
        'Xenon',
        'Other',
      ],
      Tesla: ['all', 'Model 3', 'Model S', 'Model X', 'Roadster', 'Other'],
      Toyota: [
        'all',
        '4-Runner',
        'Alphard',
        'Auris',
        'Auris Touring Sports',
        'Avalon',
        'Avensis',
        'Avensis Verso',
        'Aygo',
        'Camry',
        'Carina',
        'Celica',
        'C-HR',
        'Corolla',
        'Corolla Verso',
        'Cressida',
        'Crown',
        'Dyna',
        'FCV',
        'FJ',
        'Fortuner',
        'GT86',
        'Hiace',
        'Highlander',
        'Hilux',
        'IQ',
        'Land Cruiser',
        'Lite-Ace',
        'Matrix',
        'Mirai',
        'MR 2',
        'Paseo',
        'Picnic',
        'Previa',
        'Prius',
        'Prius+',
        'Proace (Verso)',
        'RAV 4',
        'Sequoia',
        'Sienna',
        'Starlet',
        'Supra',
        'Tacoma',
        'Tercel',
        'Tundra',
        'Urban Cruiser',
        'Verso',
        'Verso-S',
        'Yaris',
        'Other',
      ],
      Trabant: ['all', '601', 'Other'],
      Triumph: [
        'all',
        'Dolomite',
        'Moss',
        'Spitfire',
        'TR3',
        'TR4',
        'TR5',
        'TR6',
        'TR7',
        'TR8',
        'Other',
      ],
      TVR: ['all', 'Chimaera', 'Griffith', 'Tuscan', 'Other'],
      Volkswagen: [
        'all',
        '181',
        'Amarok',
        'Arteon',
        'Beetle',
        'Beetle',
        'Bora',
        'Buggy',
        'Caddy',
        'CC',
        'Corrado',
        'Crafter',
        'Eos',
        'Fox',
        'Golf',
        'Golf Plus',
        'Golf Sportsvan',
        'Iltis',
        'Jetta',
        'Karmann Ghia',
        'LT',
        'Lupo',
        'New Beetle',
        'Passat',
        'Passat Alltrack',
        'Passat CC',
        'Passat Variant',
        'Phaeton',
        'Polo',
        'Routan',
        'Santana',
        'Scirocco',
        'Sharan',
        'T1',
        'T2',
        'T3 Caravelle',
        'T3 Kombi',
        'T3 Multivan',
        'T3 other',
        'T4 California',
        'T4 Caravelle',
        'T4 Kombi',
        'T4 Multivan',
        'T4 other',
        'T5 California',
        'T5 Caravelle',
        'T5 Kombi',
        'T5 Multivan',
        'T5 other',
        'T5 Shuttle',
        'T5 Transporter',
        'T6 California',
        'T6 Caravelle',
        'T6 Kombi',
        'T6 Multivan',
        'T6 other',
        'T6 Transporter',
        'Taro',
        'T-Cross',
        'Tiguan',
        'Tiguan Allspace',
        'Touareg',
        'Touran',
        'T-Roc',
        'up!',
        'Vento',
        'XL1',
        'Other',
      ],
      Volvo: [
        'all',
        '240',
        '244',
        '245',
        '262',
        '264',
        '340',
        '360',
        '440',
        '460',
        '480',
        '740',
        '744',
        '745',
        '760',
        '780',
        '850',
        '855',
        '940',
        '944',
        '945',
        '960',
        '965',
        'Amazon',
        'C30',
        'C70',
        'Polar',
        'S40',
        'S60',
        'S60 Cross Country',
        'S70',
        'S80',
        'S90',
        'V40',
        'V40 Cross Country',
        'V50',
        'V60',
        'V60 Cross Country',
        'V70',
        'V90',
        'V90 Cross Country',
        'XC40',
        'XC60',
        'XC70',
        'XC90',
        'Other',
      ],
      Wartburg: ['all', '311', '353', 'Other'],
      Wiesmann: [
        'all',
        'MF 25',
        'MF 28',
        'MF 3',
        'MF 30',
        'MF 35',
        'MF 4',
        'MF 5',
        'Other',
      ],
      other: ['Other'],
    },
    motoScooterAtv: {
      all: {},
      ATV: {},
      moto: {},
      scooters: {},
    },
    autoUtility: {
      all: {},
      Acerbi: {},
      ACTM: {},
      Adria: {},
      Aro: {},
      Beyerland: {},
      Bluecamp: {},
      Caravelair: {},
      Chevrolet: {},
      Chrysler: {},
      Citroen: {},
      Concorder: {},
      Dacia: {},
      Daewoo: {},
      Dodge: {},
      Euramobil: {},
      Fiat: {},
      Ford: {},
      GMC: {},
      Honda: {},
      Hyundai: {},
      Isuzu: {},
      Iveco: {},
      Kenworth: {},
      Kia: {},
      Lamberet: {},
      MAN: {},
      Mazda: {},
      MercedesBenz: {},
      Miller: {},
      Mitsubishi: {},
      Nissan: {},
      Nova: {},
      Opel: {},
      Peterbilt: {},
      Peugeot: {},
      Praga: {},
      Renault: {},
      Roman: {},
      Scania: {},
      Schmitz: {},
      Scoda: {},
      SsangYong: {},
      Subaru: {},
      Sunlight: {},
      Suzuki: {},
      TEC: {},
      Toyota: {},
      Ursus: {},
      Volkswagen: {},
      Wielton: {},
      Yanmar: {},
      Zetor: {},
    },
    trucksTrailersCaravans: {
      all: {},
      trucks: {},
      trailers: {},
      caravans: {},
    },
    boats: {},
  },
  realEstate: {
    all: [],
    apartmentsForRent: [],
    apartmentsForSale: [],
    housesForRent: [],
    housesForSale: [],
    grounds: [],
    changes: [],
    accomodationTourism: [],
    officesCommercialSpaces: [],
    parkingGarage: [],
    deposits: [],
    anotherProperties: [],
  },
  electronicsAppliances: {
    all: {},
    phones: {
      all: {},
      Samsung: {},
      Apple: {},
      Allview: {},
      Htc: {},
      Sony: {},
      Nokia: {},
      Lg: {},
      Huawei: {},
      Blackberry: {},
      Lenovo: {},
      Vodafone: {},
      Orange: {},
      Alcatel: {},
      Motorola: {},
      Xiaomi: {},
      OnePlus: {},
      Google: {},
      Honor: {},
      Ihunt: {},
      Landline: {},
      PhonesWithButtonsForSeniors: {},
      Oppo: {},
      Vivo: {},
      Digi: {},
    },
    TV: {
      all: {},
      TV: {},
      TVAccesories: {},
      antens: {},
      smarts: {},
      remoteControls: {},
      cleanKits: {},
      cablesAdaptors: {},
      pieces: {},
    },
    appliances: {
      all: {},
      taylorMachine: {},
      fridges: {},
      microWave: {},
      cookers: {},
      cookerInduction: {},
      washingMachine: {},
      vacuumCleaner: {},
      dishingWasher: {},
      heatersAndJuicers: {},
      clothesDryers: {},
      espressoAndAccesories: {},
      irons: {},
      toastersAndSandwichMakers: {},
      mixersChoppersAndFoodProcessors: {},
    },
    tabletsAndReaders: {
      all: {},
      Samsung: {},
      Ipad: {},
      Allview: {},
      Asus: {},
      Kindle: {},
      Lenovo: {},
      Huawei: {},
      Microsoft: {},
      Xiaomi: {},
      Ereaders: {},
      Another: {},
    },
    phonesTabletsParts: {
      all: {},
      phoneBatteries: {},
      BandsFlexPhones: {},
      phoneCases: {},
      displayTouchscreenPhones: {},
      tabletBatteries: {},
      bandsFlexTablets: {},
      tabletCases: {},
      displayTouchscreenTablets: {},
      dismantling: {},
    },
    videoProiection: {
      all: {},
      VideoProiectionaccesories: {},
      screenProiection: {},
      interactiveTable: {},
      videoProiection: {},
    },
    webAndServers: {
      all: {},
      accesPoints: {},
      accesoriesAntens: {},
      cables: {},
      serversSystems: {},
      routers: {},
      accesoriesRouter: {},
      switches: {},
      serversComponents: {},
      stabilization: {},
    },
    laptopPcGaming: {
      all: {},
      consoleAccesories: {},
      portableConsoles: {},
      Xbox: {},
      NintendoWii: {},
      Playstation: {},
      gamesConsole: {},
      laptop: {},
      computers: {},
      monitors: {},
      gamingComponents: {},
    },
    peripheralsAccesoriesLaptopPc: {
      all: {},
      laptopAccesories: {},
      bagsBackpacksCoversLaptop: {},
      laptopCharging: {},
      standsCoolersLaptop: {},
      gamingAccesories: {},
      mousesMousepads: {},
      keyboards: {},
      speakersPc: {},
      webCameras: {},
      externHardDisksAccesories: {},
      microphonesPc: {},
      peripheralsOther: {},
      externsSSDAccesories: {},
      graphicTablets: {},
      externOpticalUnits: {},
    },
    printersScanners: {
      all: {},
      labellingDevicesAccesories: {},
      suppliesAccesories: {},
      printersMultifunctionals: {},
      scanners: {},
      other: {},
    },
    selfcare: {
      all: {},
      cosmeticDevices: {},
      shavingMachines: {},
      manicurePedicureDevices: {},
      depilatory: {},
      clippers: {},
      hairCurlers: {},
      electricHairBrushes: {},
      toothbrushes: {},
      hairStraighteners: {},
      hairDryers: {},
      anotherDevices: {},
    },
    audioHifi: {
      all: {},
      speakers: {},
      controllers: {},
      subwoofers: {},
      soundsProcessor: {},
      players: {},
      homecinema: {},
    },
    phonesTabletsAccesories: {
      all: {},
      cablesAdaptorsTablet: {},
      protectiveWrap: {},
      coversTablets: {},
      tabletsChargings: {},
      phoneAdaptors: {},
      anotherPhonesAccesories: {},
      memoryCards: {},
      screenProtectionAndPhoneWraps: {},
      phonesCover: {},
      phonesCharging: {},
      phonePowerBank: {},
      supportsDockingPhones: {},
    },
  },
  fashion: {
    all: {},
    womanClothes: {
      all: {},
      skirts: {},
      underwearCorsetsBustiers: {},
      SweatshirtsShirtsTShirts: {},
      sweaters: {},
      cardigans: {},
      hoodedSweatshirts: {},
      sweatshirts: {},
      jacketsSuits: {},
      socks: {},
      homeClothes: {},
      dressesTunics: {},
      overall: {},
      nationalPorts: {},
      outfit: {},
      shorts: {},
      jeans: {},
      sportClothes: {},
    },
    womanShoes: {
      all: {},
      shoes: {},
      boots: {},
      tallBoots: {},
      uggBoots: {},
      moccasinsBallerinas: {},
      sportShoes: {},
      sandalsSlippers: {},
      otopedicShoes: {},
      runningShoes: {},
    },
    manClothes: {
      all: {},
      sweatersHoodies: {},
      outfit: {},
      shortsTShorts: {},
      jeans: {},
      overallJean: {},
      overallSki: {},
      overallWork: {},
    },
    manShoes: {
      all: {},
      shoes: {},
      boots: {},
      sportShoes: {},
      converseSportShoes: {},
      moccasinsEspadrilles: {},
      sandalsSlippers: {},
      otopedicShoes: {},
      runningShoes: {},
    },
    wedding: {
      all: {},
      weddingShoes: {},
      weddingDress: {},
      weddingOutfit: {},
      weddingAccesories: {},
    },
    accesories: {
      all: {},
      jewelry: {},
      purseAndAccesories: {},
      backpackAndSchoolbag: {},
      walletsAndCosmeticBags: {},
      umbrellas: {},
      hairAccesories: {},
      beltsAndWaits: {},
      scarversAndGloves: {},
      glassesAndAccesories: {},
      tiesAndBowTies: {},
    },
    watches: {
      all: {},
      womanWatches: {},
      manWatches: {},
      kidsWatches: {},
      sportWatches: {},
    },
  },
  autoParts: {
    all: {},
    wheelsRimsTires: {
      all: {},
      wheelsAndRims: {},
      wheelAccesories: {},
      tires: {},
    },
    suppliesAccesories: {
      all: {},
      suppliesAccesories: {},
      oilLubricantLiquids: {},
    },
    caroseryInterior: {
      all: {},
      caroseryMirrorsHeadlight: {},
      interior: {},
    },
    mecanicElectric: {
      all: {},
      audioElectronics: {},
      climatization: {},
      gearboxClutchTransmission: {},
      directionSuspension: {},
      breaks: {},
      engineCoolingExhaust: {},
    },
    anotherParts: {
      all: {},
      equippmentsTools: {},
      other: {},
    },
    anotherVehicles: {
      all: {},
      autoUtility: {},
      trucks: {},
      trailersCaravans: {},
      moto: {},
      boats: {},
    },
    dismantlingVehicles: {
      all: {},
    },
    electricStations: {},
  },
  houseAndGarden: {
    all: {},
    furnitureDecorations: {
      all: {},
      bathroom: {},
      office: {},
      kitchen: {},
      decorations: {},
      bedroom: {},
      livingroom: {},
    },
    garden: {
      all: {},
      gardenFurniture: {},
      plantsAndSeeds: {},
      gardenTools: {},
      gatesFences: {},
      decorations: {},
      barbeque: {},
      greenhouse: {},
      pool: {},
      another: {},
    },
    constructionFurnitureMaterials: {
      all: {},
      constructionMaterials: {},
      brickwork: {},
      doorsWindows: {},
      tilesParquet: {},
      paintAdhesive: {},
      wroughtIronWork: {},
      pitTank: {},
      scaffoldingProtection: {},
      woodForFire: {},
      another: {},
    },
    thermalElectricalSanitary: {
      all: {},
      thermals: {},
      electrical: {},
      sanitary: {},
    },
    toolsWroughtIronWork: {
      all: {},
      wroughtIronWord: {},
      electricTools: {},
      toolsAndParts: {},
    },
    householdItems: {},
    metalHallsOther: {},
  },
  momsKids: {
    all: {},
    kidsClothesShoes: {
      all: {},
      kidsClothes: {},
      kidsShoes: {},
    },
    pregnantsClothes: {},
    toys: {},
    toWalk: {
      all: {},
      strollers: {},
      walkerKid: {},
      babyPouch: {},
      carSeat: {},
      other: {},
    },
    babyRoom: {
      all: {},
      furnitureBaby: {},
      bed: {},
      accesories: {},
    },
    foodCare: {
      all: {},
      babyFood: {},
      babyIgiene: {},
      babyProtection: {},
    },
    schoolItems: {},
    otherForKids: {},
  },
  sportFreeTimeArt: {
    all: {},
    airsoft: {
      all: {},
      weaponsAirsoft: {},
      accesoriesAirsoft: {},
    },
    running: {},
    climbing: {},
    basketBall: {},
    baseball: {},
    pool: {},
    box: {
      all: {},
      protectionEquipment: {},
      punchingBag: {},
    },
    bicycleFitnessSupplements: {
      all: {},
      bicycle: {},
      kidsBicycle: {},
      electricBicycle: {},
      ciclismEquipment: {},
      accesories: {},
      fitness: {},
      supplements: {},
    },
    camping: {
      all: {},
      tents: {},
      sleepingBag: {},
      hammock: {},
      cookingFood: {},
      another: {},
    },
    dansGymnastics: {
      all: {},
      ballet: {},
      sportiveDans: {},
      costumes: {},
      protectionEquipment: {},
      anotherEquipment: {},
    },
    hike: {
      all: {},
      clothesShoes: {},
      backpacks: {},
      accesories: {},
    },
    footbal: {
      all: {},
      clothesShoes: {},
      balls: {},
      accesories: {},
    },
    horseRiding: {},
    bagsTrollers: {},
    golf: {},
    karateJudo: {},
    motoEnduroAtv: {},
    hangGlinding: {},
    fishing: {
      all: {},
      clothesShoes: {},
      chairs: {},
      rods: {},
      baits: {},
      reels: {},
      accesories: {},
    },
    waterSport: {
      all: {},
      clothes: {},
      snorkeling: {},
      scubadiving: {},
      surfing: {},
      windsurfing: {},
      boats: {},
      kayacs: {},
      accesories: {},
    },
    winterSport: {
      all: {},
      clothesShoes: {},
      ski: {},
      glasses: {},
      snowboard: {},
      sleigh: {},
      skates: {},
      accesories: {},
    },
    tennis: {
      all: {},
      rackets: {},
      balls: {},
      clothesShoes: {},
    },
    archery: {},
    trampoline: {},
    scootersRollersSkateboards: {
      all: {},
      rollers: {},
      scooters: {},
      electricScooters: {},
      skateboards: {},
      hoverboards: {},
      protectionEquipment: {},
    },
    hunting: {},
    voleyBall: {},
    sportTurismEquipment: {
      all: {},
      sportEquipment: {},
      turismEquipment: {},
    },
    artCollection: {},
    entertainmentEvents: {},
    booksMoviesMusic: {
      all: {},
      booksMagazines: {},
      movies: {},
      musicInstruments: {},
      music: {},
    },
  },
  animals: {
    all: {},
    catsDogs: {
      all: {},
      cats: {},
      dogs: {},
    },
    servicesAccesories: {},
    adoption: {},
    anotherAnimals: {},
  },
  agroIndustry: {
    all: {},
    agroIndustrialMachinery: {
      all: {},
      tractors: {},
      anotherAgriculturalMachinery: {},
      agriculturalMachineryParts: {},
      industrialMachinery: {},
      industrialMachineryParts: {},
    },
    marketProducts: {
      all: {},
      dairyProducts: {},
      egs: {},
      fruitsVegetables: {},
      honeyApicolProducts: {},
      anotherProducts: {},
    },
    cerealsPlantsTrees: {
      all: {},
      cerealFeedHay: {},
      fruitTrees: {},
      seedsPlantsGarden: {},
    },
    domesticAnimals: {
      all: {},
      horses: {},
      goats: {},
      birds: {},
      sheeps: {},
      rabbit: {},
    },
    zootechnicalEquipment: {},
  },
  servicesCompanyEquipment: {
    all: {},
    transportRentServices: {
      all: {},
      freightTransport: {},
      passengerTransport: {},
      licenseTaxiUber: {},
      rentAuto: {},
    },
    autoServicesTow: {
      all: {},
      autoServices: {},
      autoTowService: {},
    },
    craftsmanConstruction: {},
    repairPcElectronics: {},
    eventsWeddingsBaptisms: {
      all: {},
      photoVideoServices: {},
      bandsArtisticMoments: {},
      floralArrangementDecorations: {},
      cateringEvents: {},
      invitationsTestimonials: {},
      limousineVintageVars: {},
      locationsRent: {},
      anotherServices: {},
    },
    coursesMeditations: {
      all: {},
      contability: {},
      cosmeticsBeauty: {},
      danceCourse: {},
      meditations: {},
      drivingSchool: {},
      anotherCourses: {},
    },
    insuranceAdvertisingIT: {},
    beautyServices: {
      all: {},
      manicurePedicure: {},
      makeupFacialTreatments: {},
      hairstyle: {},
      massageKinetotherapy: {},
      hairRemoval: {},
      fitnessNutrition: {},
      bodyRemodeling: {},
      tatoosPiercing: {},
      tanningServices: {},
      anotherBeautyService: {},
    },
    contabilityTranslation: {},
    cleaningServices: {},
    professionalEquipment: {},
    otherServices: {},
  },
};

export const steeringWheelArray = ['all', 'left', 'right'];
export const caroseryArray = [
  'all',
  'cabrio',
  'break',
  'hatchback',
  'pickup',
  'off-road',
  'minibus',
  'sedan',
  'monovolum',
  'suv',
];
export const fuelArray = [
  'all',
  'diesel',
  'petrol',
  'gas',
  'hybrid',
  'electric',
];
export const conditionArray = ['all', 'used', 'new'];
export const colourArray = [
  'all',
  'white',
  'black',
  'grey',
  'blue',
  'red',
  'green',
  'yellow',
  'orange',
  'pink',
  'beige',
  'another colour',
];
export const kmArray = [
  '1',
  '1000',
  '5000',
  '10000',
  '50000',
  '100000',
  '150000',
  '200000',
  '250000',
  '300000',
  '400000',
  '500000',
  '1000000',
  '5000000',
];
export const yearArray = [
  '1980',
  '1981',
  '1982',
  '1983',
  '1984',
  '1985',
  '1986',
  '1987',
  '1988',
  '1989',
  '1990',
  '1991',
  '1992',
  '1993',
  '1994',
  '1995',
  '1996',
  '1997',
  '1998',
  '1999',
  '2000',
  '2001',
  '2002',
  '2003',
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2022',
];
export const priceArray = [
  '500',
  '1000',
  '1500',
  '2000',
  '2500',
  '3000',
  '3500',
  '4000',
  '4500',
  '5000',
  '6000',
  '7000',
  '8000',
  '9000',
  '10000',
  '12000',
  '14000',
  '16000',
  '18000',
  '20000',
  '25000',
  '30000',
  '40000',
  '50000',
  '100000',
  '1000000',
];
export const horsePowerArray = [
  '5',
  '50',
  '60',
  '70',
  '80',
  '90',
  '100',
  '120',
  '140',
  '160',
  '180',
  '200',
  '220',
  '240',
  '260',
  '280',
  '300',
  '350',
  '400',
  '450',
  '500',
  '600',
  '700',
  '800',
  '900',
  '1000',
  '1500',
];
export const usefulTaskArray = [
  'all',
  '0,001-2,8t',
  '2,801-3,5t',
  '3,501-7,5t',
];

export const groundTypeArray = ['all', 'extravilan', 'intravilan'];
export const commerceTypeArray = ['all', 'sale', 'rent'];
export const engineArray = [
  '500',
  '1000',
  '1100',
  '1200',
  '1300',
  '1400',
  '1500',
  '1600',
  '1700',
  '1800',
  '1900',
  '2000',
  '2200',
  '2400',
  '2600',
  '2800',
  '3000',
  '3500',
  '4000',
  '5000',
  '6000',
  '7000',
  '15000',
];
export const furnishedArray = [
  'all',
  'full-furnished',
  'semi-furnished',
  'no-furnished',
];
export const roomsArray = ['all', '1', '2', '3', '4', '5', '6', 'more than 6'];
export const usefulSurfaceArray = ['50', '90', '125', '160', '210', '245'];
export const landAreaArray = ['1', '10', '100', '1000', '10000', '20000'];
export const builtAreaArray = ['1', '10', '100', '1000', '10000', '20000'];
export const floorArray = [
  'groundFloor',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
];
export const compartimentTypeArray = [
  'all',
  'decomandated',
  'semi-decomandated',
  'circular',
  'no-decomandated',
];
export const capacityArray = ['all', 'oneCar', 'moreCars'];
export const typeParkingGarageArray = ['all', 'inside', 'outside', 'garage'];

export const electronicsArray = [
  'all',
  'Phones',
  'Appliances',
  'Tablets',
  'TVs',
  'Computers',
  'Audios',
];
export const rezolutionArray = ['all', '4k', '8k', 'hd', 'full Hd', 'non Hd'];
export const brandAppliancesArray = [
  'all',
  'Arctic',
  'Beko',
  'Bosch',
  'Electrolux',
  'HotPoint',
  'Indesit',
  'Lg',
  'Samsung',
  'Siemens',
  'Whirlpool',
  'Zanussi',
  'Another',
];
export const brandTvArray = [
  'all',
  'Samsung',
  'Lg',
  'Sony',
  'Panasonic',
  'Philips',
  'Sharp',
  'Hitachi',
  'Horizon',
  'Tlc',
  'Tesla',
  'Hyundai',
  'Star-light',
  'Jvc',
  'Xiaomi',
  'Toshiba',
  'Hitachi',
  'Grundig',
  'Another',
];

export const sizeClothesArray = [
  'all',
  '32 | XXS',
  '34 | XS',
  '36 | S',
  '38-40 | M',
  '42-44 | L',
  '46-48 | XL',
  '50-54 | XXL',
  '56-58 | XXXL',
];
export const sizeShoesArray = [
  'all',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
];
export const materialArray = [
  'all',
  'leather',
  'fakeLeather',
  'textil',
  'silicon',
];
export const seasonArray = ['all', 'summer', 'autumn', 'spring', 'winter'];
export const displayArray = [
  'all',
  'analogic',
  'digital',
  'analogic-digital',
  'unspecified',
];
export const whichForArray = ['all', 'man', 'woman'];
export const waterResistanceArray = [
  'all',
  '1ATM',
  '2ATM',
  '5ATM',
  '10ATM',
  '20ATM',
  '30ATM',
  '40ATM',
  '50ATM',
  '>50ATM',
];
export const caseMaterialArray = [
  'all',
  'gold',
  'silver',
  'zircon',
  'stainless steel',
  'alama',
  'diamond',
  'titan',
  'carbon',
];
export const caseColourArray = [
  'all',
  'white',
  'yellow',
  'golden',
  'silver',
  'grey',
];
export const soleTypeArray = ['all', 'plat', 'platform', 'heels'];
export const conditionFashionArray = [
  'all',
  'wornSingleTime',
  'newWithEticket',
  'newWithoutEticket',
  'looksGood',
];
export const brandShoesArray = [
  'all',
  'Adidas',
  'Aldo',
  'Armani',
  'Asos',
  'Bershka',
  'BSB',
  'Burbery',
  'C&A',
  'Calvin Klein',
  'Converse',
  'Desigual',
  'Diesel',
  'Dior',
  'Ecco',
  'Geox',
  'Gucci',
  'Guess',
  'H&M',
  'Hugo Boss',
  'Jack&Jons',
  'Lacoste',
  'Le Coq Sportif',
  'Lee Cooper',
  "Levi's",
  'Mango',
  'Massimo Dutti',
  'Michael Kors',
  'Motivi',
  'Musette',
  'New Yorker',
  'Next',
  'Nike',
  'Nissa',
  'Only',
  'Pepe Jeans',
  'Pull&Bear',
  'Puma',
  'Ralph Lauren',
  'Reebok',
  'Stradivarius',
  'Timberland',
  'Tommy Hilfiger',
  'United Colors of Benetton',
  'Vans',
  'Vero Moda',
  'Versace',
  "Victoria's Secret",
  'Zara',
  'Another',
];
export const brandClothesArray = [
  'all',
  'Adidas',
  'Armani',
  'Asos',
  'Bershka',
  'BSB',
  'Burberry',
  'C&A',
  'Calvin Klein',
  'Desigual',
  'Diesel',
  'Dior',
  'Gucci',
  'Guess',
  'H&M',
  'Hugo Boss',
  'Jack&Jones',
  'Lacoste',
  'LeeCooper',
  "Levi's",
  'Mango',
  'MassimoDutti',
  'MichaelKors',
  'Motivi',
  'New Yorker',
  'Next',
  'Nike',
  'Pepe Jeans',
  'Pull&Bear',
  'Puma',
  'Ralph Lauren',
  'Reebok',
  'Stradivarius',
  'Timberland',
  'Tommy Hilfiger',
  'United Colors Of Benetton',
  'Vans',
  'Vero Moda',
  'Versace',
  'Zara',
  'Another',
];
export const brandWatchesArray = [
  'all',
  'Aerowatch Anne Klein',
  'Armani Exchange',
  'Armitron',
  'Atlantic',
  'Baby-G',
  'Casio',
  'Chronostar',
  'Citizen',
  'Diesel',
  'Dior',
  'Doxa',
  'Ebel Edifice',
  'Edox Elle',
  'Elysee',
  'Emporio Armani',
  'Esprit',
  'Festina',
  'Swiss',
  'Fossil',
  'G-Shock',
  'Garmin',
  'Gant',
  'Guess',
  'Seiko',
  'Hamilton',
  'Jacques Du Manoir',
  'Jaguar',
  'Karl Lagerfeld',
  'Kenneth Cole',
  'Kerbholz',
  'Lee Cooper',
  'Lotus',
  'Louis Erard',
  'Maserati',
  'Michael Kors',
  'Montblanc',
  'Morgan',
  'Nautica',
  'N83',
  'Olivia Burton',
  'Orient',
  'Pierre Cardin',
  'Pierre Lannier',
  'Police',
  'Polar',
  'Pro Trek',
  'Pulsar',
  'Q&Q',
  'Quantum',
  'Rebecca Minkoff',
  'Rolex',
  'Tag Heuer',
  'Timberland',
  'Timex',
  'Versace',
  'Wenger',
  'Zeppelin',
  'ZRC',
  'Another',
];

export const tireSizeArray = [
  'all',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
];
export const tireWidthArray = [
  'all',
  '125',
  '135',
  '145',
  '155',
  '165',
  '175',
  '185',
  '195',
  '205',
  '215',
  '225',
  '235',
  '245',
  '255',
  '265',
  '275',
  '285',
  '295',
  '305',
  '315',
  '325',
  '335',
  '345',
  '355',
];
export const tireProfileArray = [
  'all',
  '25',
  '30',
  '35',
  '40',
  '45',
  '50',
  '55',
  '60',
  '65',
  '70',
  '75',
  '80',
  '85',
  '90',
];
export const tireSeasonArray = ['all', 'allSeason', 'winter', 'summer'];
export const rimTypeArray = ['all', 'alloy', 'steel'];
export const rimSizeArray = [
  'all',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
];
export const mountTypeArray = ['all', 'onTheWall', 'independently', 'pedestal'];
export const productTypeArray = [
  'all',
  'chargingStation',
  'chargingCable',
  'batteryCharger',
];
export const chargeTypeArray = [
  'all',
  'singlePhaseCurrent',
  'threePhaseCurrent',
  'alternativeCurrent',
];
export const useArray = ['all', 'commercial', 'householdUse'];

export const ageArray = [
  'all',
  '0-12 mounth',
  '12-24 mounth',
  '2-4 years',
  '4-8 years',
  '8-12 years',
];
export const ageAnimalsArray = [
  'all',
  '1-6 months',
  '6-12 months',
  '1-3 years',
  '3-5 years',
  '5-10 years',
  'over 10 years',
];

export const guaranteeArray = ['all', 'guarantee', 'no-guarantee'];
export const availabilityArray = ['all', 'nonstop', 'programmingOnly'];
export const experienceArray = [
  'all',
  '1-3 years',
  '3-6 years',
  '6-9 years',
  'over 10 years',
];
export const operationDistanceArray = [
  'all',
  '25km',
  '50km',
  '250km',
  'allTheCountry',
  'international',
];
export const autoServicesArray = [
  'all',
  'detailing/polish',
  'painting',
  'mechanics',
  'diagnostics',
  'electronics/Audio',
  'conditioning',
  'washing/cleaning',
  'vulcanization',
  'directionAdjustment',
  'wheels',
  'others',
];
export const emergencyServiceArray = [
  'all',
  'emergencyService',
  'non-emergencyService',
];
export const financePosibilityArray = [
  'all',
  'possibleFinance',
  'notPossibleFinance',
];

export const compatibilityArray = [
  'all',
  'PC',
  'PS3',
  'PS4',
  'PSP',
  'Wii',
  'Wii U',
  'Xbox 360',
  'Xbox One',
  'Another',
];
export const laptopProcesorBrandArray = [
  'all',
  'Intel',
  'Amd',
  'Apple',
  'Qualcomm',
  'MediaTek',
];
export const sizeDiagonalArray = [
  'all',
  "under 11'",
  "11'-12.9'",
  "13'-13.9'",
  "14'-14.9'",
  "15'-15.6'",
  "over 15.6'",
];
export const memoryRArray = [
  'all',
  '< 4Gb',
  '4-6Gb',
  '6-8Gb',
  '8-10Gb',
  '10-16Gb',
  '>16Gb',
];
export const videoTypeArray = ['all', 'integrated', 'dedicated'];
export const storageTypeArray = ['all', 'SSD + HDD', 'SSD', 'HDD'];
export const laptopBrandArray = [
  'all',
  'Asus',
  'Alienware',
  'Lenovo',
  'Hp',
  'Acer',
  'Dell',
  'Msi',
  'Gigabyte',
  'Razer',
  'Samsung',
  'Microsoft',
  'Apple',
  'Google',
  'Huawei',
  'Myria',
  'Sony',
  'Another',
];
export const playstationArray = [
  'all',
  'Playstation',
  'Playstation 2',
  'Playstation 3',
  'Playstation 4',
  'Playstation 5',
  'Portable Playstation',
  'Playstation Vita',
];
export const xboxArray = [
  'all',
  'Xbox',
  'Xbox 360',
  'Xbox One',
  'Xbox X Series',
  'Xbox S Series',
];
export const nintendoArray = [
  'all',
  'WiiWhiteModel',
  'WiiBlackModel',
  'WiiRedModel',
  'WiiBlueModel',
  'WiiFamilyEdition',
  'WiiMini',
];